name: Save single output to GitHub

on:
  schedule:
    - cron: "0 0 * * 6"  # Weekly on Saturday at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  save-single-output:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Caching pipenv dependencies:
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - run: pipenv install

    - name: Run program in single mode and generate output
      run: |
        pipenv run python script/kfc.py --mode single
        mv -f single.js js/single.js

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'js/single.js'
        message: 'weekly update single product information'
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com

    - name: Archive log file
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: debug-log-single
        path: debug.log
        retention-days: 30
